# Use site.<name> to read the stuff from here.

title: Italian C++ Conference 2021
# Stick to ISO 8601 - will be used for time conversion.
date: 2021-06-19
place: # Included in intro image. Online

description: > # this means to ignore newlines until "baseurl:"
  The biggest online event about C++ development organized with passion by the Italian C++ Community. Original live keynote by Sean Parent, 12 live tech sessions, virtual networking space open all day long. Free to attend.
baseurl: "" # the subpath of your site, e.g. /blog
url: "italiancpp.github.io" # the base hostname & protocol for your site

# Allowed values: cfs, reservation speakers, agenda.
sections: ['reservation', 'speakers', 'agenda']

general_feedback: "https://forms.gle/rctcxe9jou87TydF8"
eventbrite_id: "150150445023"

# Build settings
markdown: kramdown


logo: "https://raw.githubusercontent.com/italiancpp/misc/master/logo/logo_completo.png"
contact_url: mailto:info@italiancpp.org

#Image in the header
poster: locandina-itcppcon21-fullsize.gif

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: []

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames 
social:
  - title: desktop
    url: https://www.italiancpp.org
  - title: facebook
    url: https://www.facebook.com/italiancpp/
  - title: twitter
    url: https://twitter.com/italiancpp
  - title: linkedin
    url: https://www.linkedin.com/company/italiancpp
    

# Build settings
markdown: kramdown
permalink: pretty
