# Use site.<name> to read the stuff from here.

title: Italian C++ Conference 2021
date: # Included in intro image. 19th June 2021
place: # Included in intro image. Online

description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown


logo: "https://raw.githubusercontent.com/italiancpp/misc/master/logo/logo_completo.png"
contact_url: mailto:info@italiancpp.org

#Image in the header
poster: locandina-itcppcon21-fullsize.png

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames 
social:
  - title: facebook
    url: https://www.facebook.com/italiancpp/
  - title: twitter
    url: https://twitter.com/italiancpp
  - title: linkedin
    url: https://www.linkedin.com/company/italiancpp

# Build settings
markdown: kramdown
permalink: pretty
